<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>

    <!-- dimensions of a motor -->
    <xacro:property name="motorlength" value="0.066" />
    <xacro:property name="motorwidth" value="0.018" />
    <xacro:property name="motorheight" value="0.023" />

    <!-- dimensions of a wheel -->
    <xacro:property name="wheelwidth" value="0.025" />
    <xacro:property name="wheeldiameter" value="0.065" />

    <material name="motorbox">
        <color rgba="1.0 1.0 0.0 1.0" />
    </material>

    <material name="wheel">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>

    <!-- Macro for joints between base and drive_unit -->
    <xacro:macro name="drive_joint" params="base prefix rotateX rotateY rotateZ moveX moveY moveZ">
        <joint name="${prefix}_drive_unit_joinz" type="fixed">
            <parent link="${base}" />
            <child link="${prefix}_motorbox" />
            <origin rpy="${rotateX} ${rotateY} ${rotateZ}" xyz="${moveX} ${moveY} ${moveZ-motorheight/2}" />
        </joint>
    </xacro:macro>

    <!-- Macro for drive_unit including motor, gearbox, wheel -->
    <xacro:macro name="drive_unit" params="prefix">
        <link name="${prefix}_motorbox">
            <visual>
                <origin xyz="${-motorlength/3} ${-motorwidth/2} 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${motorlength} ${motorwidth} ${motorheight}" />
                </geometry>
                <material name="motorbox" />
            </visual>
            <collision>
                <origin xyz="${-motorlength/3} ${-motorwidth/2} 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${motorlength} ${motorwidth} ${motorheight}" />
                </geometry>
            </collision>
        <xacro:inertial_box mass="0.035" x="${motorlength}" y="${motorwidth}" z="${motorheight}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="${prefix}_motorbox" />
            <child link="${prefix}_wheel" />
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 ${(motorwidth+wheelwidth)/2} 0.0" />
            <axis rpy="0.0 0.0 0.0" xyz="0.0 0.0 1" />
        </joint>

        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheeldiameter/2}" length="${wheelwidth}" />
                </geometry>
                <material name="wheel" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheeldiameter/2}" length="${wheelwidth}" />
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="0.010" length="${wheelwidth}" radius="${wheeldiameter/2}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>
    </xacro:macro>

</robot>