#!/usr/bin/env python3


import rclpy
from rclpy.node import Node

from geometry_msgs.msg import Twist
from geometry_msgs.msg import Quaternion


class Control(Node):
    '''
    Main control node for nodebot1.
    Propagates cmd_vel command for nodebot1 to nodebot1's chassis.

    '''
    def __init__(self):
        super().__init__('control')
        # subscription for cmd_vel in namespace of nodebot1
        self.cmd_vel_subscription = self.create_subscription(
            Twist,
            '/nodebot1/cmd_vel',
            self.listener_cmd_vel_callback,
            10)
        self.cmd_vel_subscription  # prevent unused variable warning

        # subscription for cmd_vel in namespace of nodebot1
        self.cmd_cam_subscription = self.create_subscription(
            Quaternion,
            '/nodebot1/cmd_cam',
            self.listener_cmd_cam_callback,
            10)
        self.cmd_cam_subscription  # prevent unused variable warning
        
        # publisher for cmd_vel in local namespace chassis
        self.cmd_vel_publisher = self.create_publisher(Twist, '/local/chassis/cmd_vel', 10)

        # publisher for cmd_cam in local namespace chassis
        self.cmd_cam_publisher = self.create_publisher(Quaternion, '/local/cmd_cam', 10)


    def listener_cmd_vel_callback(self, msg):
        self.get_logger().debug('/nodebot1/cmd_vel: "%s"' % msg)
        # re-publish received cmd_vel message
        self.cmd_vel_publisher.publish(msg)


    def listener_cmd_cam_callback(self, msg):
        self.get_logger().debug('/nodebot1/cmd_cam: "%s"' % msg)
        # re-publish received cmd_vel message
        self.cmd_cam_publisher.publish(msg)



def main(args=None):
    rclpy.init(args=args)

    control = Control()

    rclpy.spin(control)

    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    control.destroy_node()
    rclpy.shutdown()



if __name__ == '__main__':
    main()
